services:
  mobile-backend:
    build: ./mobile_backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/parking_spot_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./mobile_backend:/app
    command: sh -c "go run ."
    working_dir: /app

  ai-service:
    build: ./ai_service
    ports:
      - "8000:8000"
    environment:
      allow_origins: '["http://localhost:3000", "http://parking-spot-interface:3000"]'
      allow_methods: '["*"]'
      allow_headers: '["*"]'
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/parking_spot_db
      REDIS_URL: redis://redis:6379
      REDIS_OCCUPANCY_TTL_SECONDS: 60
      CACHE_TTL_SECONDS: 300
      IOU_THRESHOLD: 0.3
    volumes:
      - ./ai_service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis

  parking-spot-interface:
    build:
      context: ./parking_spot_interface
      target: deps
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://ai-service:8000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/parking_spot_db
      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: parking-spot-images
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - ai-service
      - postgres
      - localstack
    volumes:
      - ./parking_spot_interface:/app
      - /app/node_modules
    command: sh -c "pnpm run dev"
    working_dir: /app

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_spot_db
    volumes:
      - ./postgres_data:/var/lib/postgresql

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
    volumes:
      - ./localstack_data:/var/lib/localstack
